### ISSUE TITLE
TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by lucie01** [shystruk/create-react-redux-app-structure#10]
When I wrote the code "create-react-redux-app-structure my-app", I received this message:

Welcome to Create React Redux App Structure
----------------------------------------------------------
Installing Packages
----------------------------------------------------------
child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:493:38)
    at Object.<anonymous> (C:\Users\lucie\AppData\Roaming\npm\node_modules\create-react-redux-app-structure\cli\cli.js:15:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)

**Comment by shystruk** [comment]
@lucie01 as you are not responding to 9 days I close that issue.
If you still have that problem please check issue #11

Thanks!
