### ISSUE TITLE
Application Created doesn't compile properly on Ubuntu

### ISSUE THREAD

**Issue by VittorioAccomazzi** [shystruk/create-react-redux-app-structure#34]
The application created doesn't compile properly. Here is what I get when I run the *fast-start* as soon as the application is created : 

```
$ npm run fast-start

> create-react-redux-app-structure@4.6.0 fast-start /home/vittorio/Projects/myApp
> yarn install && webpack --mode=development && gulp prod && run-p server open-localhost

yarn install v1.21.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.79s.
Hash: efc7d2b521c2bd197ebc
Version: webpack 4.41.5
Time: 3661ms
Built at: 01/01/2020 6:28:23 AM
                        Asset      Size                  Chunks                   Chunk Names
    custom_elements_vendor.js  4.79 KiB  custom_elements_vendor  [emitted]        custom_elements_vendor
custom_elements_vendor.js.map  4.57 KiB  custom_elements_vendor  [emitted] [dev]  custom_elements_vendor
                     index.js  2.28 MiB                   index  [emitted]        index
                 index.js.map  2.33 MiB                   index  [emitted] [dev]  index
                    vendor.js  1.49 MiB                  vendor  [emitted]        vendor
                vendor.js.map  1.65 MiB                  vendor  [emitted] [dev]  vendor
Entrypoint index = index.js index.js.map
Entrypoint vendor = vendor.js vendor.js.map
Entrypoint custom_elements_vendor = custom_elements_vendor.js custom_elements_vendor.js.map
[0] multi babel-polyfill ./app/app.jsx 40 bytes {index} [built]
[1] ../locale-data/index.js (ignored) 15 bytes {index} {vendor} [built]
[2] ./lib/locales (ignored) 15 bytes {index} {vendor} [built]
[3] ./lib/locales (ignored) 15 bytes {index} {vendor} [built]
[4] multi react react-dom react-router-dom react-redux react-intl redux redux-promise redux-thunk redux-logger 124 bytes {vendor} [built]
[5] multi ./app/vendor/custom-elements-es5-adapter.js 28 bytes {custom_elements_vendor} [built]
[./app/actions/notification.js] 617 bytes {index} [built]
[./app/app.jsx] 2.06 KiB {index} [built]
[./app/constants/events.constant.js] 190 bytes {index} [built]
[./app/helpers/domReady.js] 3.14 KiB {index} [built]
[./app/i18n/messages.js] 583 bytes {index} [built]
[./app/pages/App.jsx] 9.12 KiB {index} [built]
[./app/store.js] 1.13 KiB {index} [built]
[./app/vendor/custom-elements-es5-adapter.js] 468 bytes {custom_elements_vendor} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {index} {vendor} [built]
    + 643 hidden modules
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/vittorio/Projects/myApp/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/vittorio/Projects/myApp/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/vittorio/Projects/myApp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-redux-app-structure@4.6.0 fast-start: `yarn install && webpack --mode=development && gulp prod && run-p server open-localhost`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the create-react-redux-app-structure@4.6.0 fast-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vittorio/.npm/_logs/2020-01-01T11_28_23_884Z-debug.log
```
$ node -v
v12.14.0
$ npm -v
6.13.4
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
and the [packages installed](https://github.com/shystruk/create-react-redux-app-structure/files/4013995/dependencies.txt)

**Comment by VittorioAccomazzi** [comment]
**Identified the problem**
Upon further analysis I figured out that the problem is that on my machine I don't have *yarn* installed. After [install it manually I](https://yarnpkg.com/lang/en/docs/install/#debian-stable) was able to run create-react-redux-app-structure successfully. I suggest to add this information on the documentation.

**Comment by VittorioAccomazzi** [comment]
**more problem**
The application created doesn't compile properly. Here is what I get when I run the *fast-start* as soon as the application is created : 

`
$ npm run fast-start

> create-react-redux-app-structure@4.6.0 fast-start /home/vittorio/Projects/myApp
> yarn install && webpack --mode=development && gulp prod && run-p server open-localhost

yarn install v1.21.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.79s.
Hash: efc7d2b521c2bd197ebc
Version: webpack 4.41.5
Time: 3661ms
Built at: 01/01/2020 6:28:23 AM
                        Asset      Size                  Chunks                   Chunk Names
    custom_elements_vendor.js  4.79 KiB  custom_elements_vendor  [emitted]        custom_elements_vendor
custom_elements_vendor.js.map  4.57 KiB  custom_elements_vendor  [emitted] [dev]  custom_elements_vendor
                     index.js  2.28 MiB                   index  [emitted]        index
                 index.js.map  2.33 MiB                   index  [emitted] [dev]  index
                    vendor.js  1.49 MiB                  vendor  [emitted]        vendor
                vendor.js.map  1.65 MiB                  vendor  [emitted] [dev]  vendor
Entrypoint index = index.js index.js.map
Entrypoint vendor = vendor.js vendor.js.map
Entrypoint custom_elements_vendor = custom_elements_vendor.js custom_elements_vendor.js.map
[0] multi babel-polyfill ./app/app.jsx 40 bytes {index} [built]
[1] ../locale-data/index.js (ignored) 15 bytes {index} {vendor} [built]
[2] ./lib/locales (ignored) 15 bytes {index} {vendor} [built]
[3] ./lib/locales (ignored) 15 bytes {index} {vendor} [built]
[4] multi react react-dom react-router-dom react-redux react-intl redux redux-promise redux-thunk redux-logger 124 bytes {vendor} [built]
[5] multi ./app/vendor/custom-elements-es5-adapter.js 28 bytes {custom_elements_vendor} [built]
[./app/actions/notification.js] 617 bytes {index} [built]
[./app/app.jsx] 2.06 KiB {index} [built]
[./app/constants/events.constant.js] 190 bytes {index} [built]
[./app/helpers/domReady.js] 3.14 KiB {index} [built]
[./app/i18n/messages.js] 583 bytes {index} [built]
[./app/pages/App.jsx] 9.12 KiB {index} [built]
[./app/store.js] 1.13 KiB {index} [built]
[./app/vendor/custom-elements-es5-adapter.js] 468 bytes {custom_elements_vendor} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {index} {vendor} [built]
    + 643 hidden modules
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/vittorio/Projects/myApp/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/vittorio/Projects/myApp/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/vittorio/Projects/myApp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-react-redux-app-structure@4.6.0 fast-start: `yarn install && webpack --mode=development && gulp prod && run-p server open-localhost`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the create-react-redux-app-structure@4.6.0 fast-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vittorio/.npm/_logs/2020-01-01T11_28_23_884Z-debug.log

`
